#!/usr/bin/env bash
#
# Ensure you have CMake installed, modern OpenALSoft
# compiling requires it.
#
# If you want to build Platinum as a shared library, edit the
# "-DLIBTYPE" flag in the cmake build step for OpenAL-Soft

EXTERNAL=external
mkdir -p "$EXTERNAL"

echo "Fetching stb headers..."
curl -sL "https://raw.githubusercontent.com/nothings/stb/master/stb_image.h" \
    -o "$EXTERNAL/stb_image.h"
curl -sL "https://raw.githubusercontent.com/nothings/stb/master/stb_truetype.h" \
    -o "$EXTERNAL/stb_truetype.h"
curl -sL "https://raw.githubusercontent.com/nothings/stb/master/stb_perlin.h" \
    -o "$EXTERNAL/stb_perlin.h"

# rxi microtar code
if [ ! -d "$EXTERNAL/mtar" ]; then
    mkdir -p "$EXTERNAL/mtar"
    echo "Fetching microtar..."
    curl -sL "https://raw.githubusercontent.com/rxi/microtar/master/src/microtar.c" \
        -o "$EXTERNAL/mtar/microtar.c"
    curl -sL "https://raw.githubusercontent.com/rxi/microtar/master/src/microtar.h" \
        -o "$EXTERNAL/mtar/microtar.h"
else
    echo "microtar fetched, skipping..."
fi


# OpenAL requires CMake
if [ ! -d "$EXTERNAL/openal-soft" ]; then
    echo "Fetching openal-soft..."
    git clone --depth=1 https://github.com/kcat/openal-soft.git "$EXTERNAL/openal-soft"
else
    echo "openal-soft already fetched, skipping..."
fi

echo "Building openal-soft..."
cmake -S "$EXTERNAL/openal-soft" \
      -B "$EXTERNAL/openal-soft/build" \
      -DCMAKE_BUILD_TYPE=Release \
      -DLIBTYPE=STATIC \
      -DALSOFT_EXAMPLES=OFF \
      -DALSOFT_TESTS=OFF \
      -DALSOFT_UTILS=OFF
cmake --build "$EXTERNAL/openal-soft/build" --parallel